### ISSUE TITLE
Build: Beamup latency causes timeout responses

### ISSUE THREAD

**Issue by maormagori** [maormagori/ktuvit-stremio#28]
This is an urgent issue,
Currently, the addon is successfully deployed to Beamup. Each call is working fine returning 200 with the requested content.
After a few minutes something breaks, and we either get a cached response or a 504. 
**This is causing the addon to be unusable in its current state**

I would have treated this immediately but I don't have the time now so I'm opening this up for anyone looking for answers.

**Comment by maormagori** [comment]
Testing proves that the problem is not with the addon but with the Beamup servers.
I sent a message to the Beamup guys but for now, we'll have to deal with the current state.

If anyone knows a free hosting alternative, let me know.

**Comment by maormagori** [comment]
Edited title to better represent the issue.

**Comment by maormagori** [comment]
As stated in #33 I changed hosting to Render.com. In theory, this solves this issue so I'm closing this for now and will open it again if proven to be wrong.

**Comment by maormagori** [comment]
Reopening for now.

**Comment by maormagori** [comment]
So it turns out we did have a problem in our code but because Beamup logs are not up to date we never got to see the error message. The new provider (That unfortunately we might leave) gives us a glimpse of what's going on.

<details open>
<summary>Log</summary>
<be>
<pre>
Apr 22 10:27:54 PM  ==> Starting service with 'node index.js'
Apr 22 10:28:04 PM  22-04-2023 19:28:04 [info]: Starting initialization.
Apr 22 10:28:05 PM  22-04-2023 19:28:05 [info]: Started addon on: https://ktuvit-stremio.onrender.com:10000
Apr 22 10:38:37 PM  22-04-2023 19:38:37 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:38:50 PM  22-04-2023 19:38:50 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:39:36 PM  22-04-2023 19:39:36 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:40:16 PM  22-04-2023 19:40:16 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:40:55 PM  22-04-2023 19:40:55 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:41:26 PM  22-04-2023 19:41:26 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:47:53 PM  22-04-2023 19:47:53 [error]: Unable to get title's ktuvit ID
Apr 22 10:48:47 PM  22-04-2023 19:48:47 [error]: Unable to get title's ktuvit ID
Apr 22 10:48:47 PM  22-04-2023 19:48:47 [error]: Unable to get title's ktuvit ID
Apr 22 10:49:20 PM  22-04-2023 19:49:20 [error]: Unable to get title's ktuvit ID
Apr 22 10:49:37 PM  22-04-2023 19:49:37 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:49:38 PM  22-04-2023 19:49:38 [error]: Unable to get title's ktuvit ID
Apr 22 10:49:53 PM  22-04-2023 19:49:53 [error]: Unable to get title's ktuvit ID
Apr 22 10:50:40 PM  22-04-2023 19:50:40 [error]: Unable to get title's ktuvit ID
Apr 22 10:50:48 PM  22-04-2023 19:50:48 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:51:53 PM  22-04-2023 19:51:53 [error]: Unable to get title's ktuvit ID
Apr 22 10:53:32 PM  22-04-2023 19:53:32 [error]: Unable to get title's ktuvit ID
Apr 22 10:53:43 PM  22-04-2023 19:53:43 [error]: Unable to get title's ktuvit ID
Apr 22 10:53:56 PM  22-04-2023 19:53:56 [error]: Unable to get title's ktuvit ID
Apr 22 10:54:00 PM  22-04-2023 19:54:00 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:54:17 PM  22-04-2023 19:54:17 [error]: Unable to get title's ktuvit ID
Apr 22 10:54:53 PM  22-04-2023 19:54:53 [error]: Unable to get title's ktuvit ID
Apr 22 10:54:56 PM  22-04-2023 19:54:56 [error]: Unable to get title's ktuvit ID
Apr 22 10:55:02 PM  22-04-2023 19:55:02 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:55:15 PM  22-04-2023 19:55:15 [error]: Unable to get title's ktuvit ID
Apr 22 10:55:31 PM  22-04-2023 19:55:31 [error]: Unable to get title's ktuvit ID
Apr 22 10:55:38 PM  22-04-2023 19:55:38 [error]: Unable to get title's ktuvit ID
Apr 22 10:55:43 PM  22-04-2023 19:55:43 [error]: Unable to get title's ktuvit ID
Apr 22 10:55:56 PM  22-04-2023 19:55:56 [error]: Unable to get title's ktuvit ID
Apr 22 10:55:59 PM  22-04-2023 19:55:59 [error]: Unable to get title's ktuvit ID
Apr 22 10:56:46 PM  22-04-2023 19:56:46 [error]: Error occurred while fetching title subs from ktuvit:  Cannot read property 'innerHTML' of null
Apr 22 10:56:46 PM  22-04-2023 19:56:46 [error]: Unable to get title's ktuvit ID
Apr 22 10:56:57 PM  22-04-2023 19:56:57 [error]: Unable to get title's ktuvit ID
Apr 22 10:57:06 PM  22-04-2023 19:57:06 [error]: Unable to get title's ktuvit ID
Apr 22 10:57:11 PM  22-04-2023 19:57:11 [error]: Unable to get title's ktuvit ID
Apr 22 10:57:12 PM  22-04-2023 19:57:12 [error]: Unable to get title's ktuvit ID
Apr 22 10:58:46 PM  22-04-2023 19:58:46 [error]: Unable to get title's ktuvit ID
Apr 22 10:59:10 PM  22-04-2023 19:59:10 [error]: Unable to get title's ktuvit ID
Apr 22 10:59:32 PM  22-04-2023 19:59:32 [error]: Unable to get title's ktuvit ID
Apr 22 11:00:37 PM  22-04-2023 20:00:37 [error]: Unable to get title's ktuvit ID
Apr 22 11:02:27 PM  22-04-2023 20:02:27 [error]: Unable to get title's ktuvit ID
Apr 22 11:02:29 PM  /opt/render/project/src/node_modules/ktuvit-api/ktuvitManager.js:181
Apr 22 11:02:29 PM                      item.name = inf.meta.name;
Apr 22 11:02:29 PM                                           ^
Apr 22 11:02:29 PM  
Apr 22 11:02:29 PM  TypeError: Cannot read property 'name' of null
Apr 22 11:02:29 PM      at /opt/render/project/src/node_modules/ktuvit-api/ktuvitManager.js:181:42
Apr 22 11:02:29 PM      at /opt/render/project/src/node_modules/name-to-imdb/index.js:59:9
Apr 22 11:02:29 PM      at /opt/render/project/src/node_modules/named-queue/index.js:27:50
Apr 22 11:02:29 PM      at Array.forEach (<anonymous>)
Apr 22 11:02:29 PM      at /opt/render/project/src/node_modules/named-queue/index.js:27:24
Apr 22 11:02:29 PM      at nextProv (/opt/render/project/src/node_modules/name-to-imdb/index.js:72:20)
Apr 22 11:02:29 PM      at /opt/render/project/src/node_modules/name-to-imdb/index.js:85:17
Apr 22 11:02:29 PM      at fail (/opt/render/project/src/node_modules/name-to-imdb/providers/imdbFind.js:28:29)
Apr 22 11:02:29 PM      at retry (/opt/render/project/src/node_modules/name-to-imdb/providers/imdbFind.js:36:57)
Apr 22 11:02:29 PM      at /opt/render/project/src/node_modules/name-to-imdb/providers/imdbFind.js:50:13
Apr 22 11:02:38 PM  ==> Starting service with 'node index.js'
Apr 22 11:02:48 PM  22-04-2023 20:02:48 [info]: Starting initialization.
Apr 22 11:02:48 PM  22-04-2023 20:02:48 [info]: Started addon on: https://ktuvit-stremio.onrender.com:10000
Apr 22 11:03:12 PM  22-04-2023 20:03:12 [error]: Unable to get title's ktuvit ID
Apr 22 11:03:35 PM  22-04-2023 20:03:35 [error]: Unable to get title's ktuvit ID
Apr 22 11:03:49 PM  22-04-2023 20:03:49 [error]: Unable to get title's ktuvit ID
Apr 22 11:04:19 PM  22-04-2023 20:04:19 [error]: Unable to get title's ktuvit ID
Apr 22 11:04:42 PM  22-04-2023 20:04:42 [error]: Unable to get title's ktuvit ID
Apr 22 11:05:44 PM  /opt/render/project/src/node_modules/ktuvit-api/ktuvitManager.js:181
Apr 22 11:05:44 PM                      item.name = inf.meta.name;
Apr 22 11:05:44 PM                                           ^
Apr 22 11:05:44 PM  
Apr 22 11:05:44 PM  TypeError: Cannot read property 'name' of null
Apr 22 11:05:44 PM      at /opt/render/project/src/node_modules/ktuvit-api/ktuvitManager.js:181:42
Apr 22 11:05:44 PM      at /opt/render/project/src/node_modules/name-to-imdb/index.js:59:9
Apr 22 11:05:44 PM      at /opt/render/project/src/node_modules/named-queue/index.js:27:50
Apr 22 11:05:44 PM      at Array.forEach (<anonymous>)
Apr 22 11:05:44 PM      at /opt/render/project/src/node_modules/named-queue/index.js:27:24
Apr 22 11:05:44 PM      at nextProv (/opt/render/project/src/node_modules/name-to-imdb/index.js:72:20)
Apr 22 11:05:44 PM      at /opt/render/project/src/node_modules/name-to-imdb/index.js:85:17
Apr 22 11:05:44 PM      at fail (/opt/render/project/src/node_modules/name-to-imdb/providers/imdbFind.js:28:29)
Apr 22 11:05:44 PM      at retry (/opt/render/project/src/node_modules/name-to-imdb/providers/imdbFind.js:36:57)
Apr 22 11:05:44 PM      at /opt/render/project/src/node_modules/name-to-imdb/providers/imdbFind.js:50:13
Apr 22 11:06:07 PM  ==> Starting service with 'node index.js'
</pre>
</details>

As you can see the container does crash. I'm unsure what are all the `Unable to get title's ktuvit ID` since no one made requests at that time. But the important part right now is the one crashing the container which is the ` Cannot read property 'name' of null`. You see the ktuvit-api searches for the title's name using its IMDB ID. There is no checking whether the result is null or not. Therefore the promise throws an error and does not get rejected, meaning the program crashes without any catches around it.

The best strategy for now is:
1. Recreate the issue locally
2. Push relevant fixes to Ktuvit-api
3. Revert this Repo to use beamup again (It's better for us I swear)
4. Update the ktuvit-api module in this repo
5. Kiss it and ship it. deployment should hopefully work again.

**Comment by maormagori** [comment]
Fixed the null pointer exception in [this pr](https://github.com/maormagori/Ktuvit-api/pull/8).

**Comment by maormagori** [comment]
Updated ktuvit-api dependency in #35.
Let's give it 24H before closing this one
